Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plot = topomap_2d.plot_topomap_2d(
    epoch,
    timestamp=timestamp
)
plot;
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-12-3b1df23f1b5a>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m plot = topomap_2d.plot_topomap_2d(
[0m[1;32m      2[0m     [0mepoch[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m     [0mtimestamp[0m[0;34m=[0m[0mtimestamp[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m )
[1;32m      5[0m [0mplot[0m[0;34m;[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/mds/simpl_eeg_capstone/simpl_eeg/topomap_2d.py[0m in [0;36mplot_topomap_2d[0;34m(epoch, plotting_data, recording_number, colormap, colorbar, cmin, cmax, mark, timestamp, **kwargs)[0m
[1;32m    149[0m [0;34m[0m[0m
[1;32m    150[0m     [0;32mif[0m [0mtype[0m[0;34m([0m[0mtimestamp[0m[0;34m)[0m [0;32mis[0m [0;32mnot[0m [0mbool[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 151[0;31m         raise TypeError(
[0m[1;32m    152[0m                 """Passed timestamp object is not in the correct format, 
[1;32m    153[0m                 please pass a bool (True or False) instead"""

[0;31mTypeError[0m: Passed timestamp object is not in the correct format, 
                please pass a bool (True or False) instead
TypeError: Passed timestamp object is not in the correct format, 
                please pass a bool (True or False) instead

